# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AllCli < Formula
  desc "Inspect and manage common CLI tool contexts"
  homepage "https://github.com/oldwinter/all-cli"
  version "0.0.0-3.1.f9b4869"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-3.1.f9b4869/all-cli_0.0.0-3.1.f9b4869_darwin_amd64.tar.gz"
      sha256 "9dc7a9fff3dc245fd7187194fff7e4e0a2559dfcdc7d98aba77505a29e178b4c"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-3.1.f9b4869/all-cli_0.0.0-3.1.f9b4869_darwin_arm64.tar.gz"
      sha256 "7f6874b930faf92a088b014d17ef7419c5111fc241d06470299c08f870fc8833"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-3.1.f9b4869/all-cli_0.0.0-3.1.f9b4869_linux_amd64.tar.gz"
      sha256 "eaf36ebdeb260a2b385458c53cf9aff3d7aeaac8aeb79e74d2cfa575cc19169f"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-3.1.f9b4869/all-cli_0.0.0-3.1.f9b4869_linux_arm64.tar.gz"
      sha256 "f02afb3e786bad5d0f81b48e2bcfdb8b7adcbda28c88851feee4ae1b44d32ade"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  test do
    system "#{bin}/all-cli", "version"
  end
end
