# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AllCli < Formula
  desc "Inspect and manage common CLI tool contexts"
  homepage "https://github.com/oldwinter/all-cli"
  version "0.0.0-1.1.f5defc7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-1.1.f5defc7/all-cli_0.0.0-1.1.f5defc7_darwin_amd64.tar.gz"
      sha256 "6e2810d95425f2d0eaa562fcd4036fecd1e81b4fe4366eee245a2031ae421fd9"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-1.1.f5defc7/all-cli_0.0.0-1.1.f5defc7_darwin_arm64.tar.gz"
      sha256 "7c21e9d97c7eeb3840b4359b867f4714ff9753565fc1d61e441c4015906812a6"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-1.1.f5defc7/all-cli_0.0.0-1.1.f5defc7_linux_amd64.tar.gz"
      sha256 "09b2065d47df458dd964a3e85b3767e9310ca526022fdca71d9443ff47fceb56"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-1.1.f5defc7/all-cli_0.0.0-1.1.f5defc7_linux_arm64.tar.gz"
      sha256 "7e9c516d08db8643c47e779ab51067b8f495f890c60c6a1bbefdfd0ee478ad52"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  test do
    system "#{bin}/all-cli", "version"
  end
end
