# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AllCli < Formula
  desc "Inspect and manage common CLI tool contexts"
  homepage "https://github.com/oldwinter/all-cli"
  version "0.0.0-2.1.73b07cc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-2.1.73b07cc/all-cli_0.0.0-2.1.73b07cc_darwin_amd64.tar.gz"
      sha256 "643863a03bdf9756d982c8018bdfe7bad5f1de9410a0f521a3336daa8a411662"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-2.1.73b07cc/all-cli_0.0.0-2.1.73b07cc_darwin_arm64.tar.gz"
      sha256 "db5383994797e9ddb4b36ec71781375dbbfbc76d212db95b70de3a3f06992259"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-2.1.73b07cc/all-cli_0.0.0-2.1.73b07cc_linux_amd64.tar.gz"
      sha256 "f590fc8a992b5334552e94768ae3a7fce611bbc7effb5e2d6f66ff301466dab3"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-2.1.73b07cc/all-cli_0.0.0-2.1.73b07cc_linux_arm64.tar.gz"
      sha256 "dcb3aef5d042261f188817c4ef66f4903255638c22002ff13918089707fa414c"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  test do
    system "#{bin}/all-cli", "version"
  end
end
