# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangCli < Formula
  desc "LLM-friendly Go CLI toolkit for HTTP, files, DB, JSON, and encoding"
  homepage "https://github.com/oldwinter/golang-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/golang-cli/releases/download/v0.1.0/golang-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "1aec4c06629987deefbe5cab2faaa4a47b4980ace9c56c281347af57b8d31071"

      def install
        bin.install "golang-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/golang-cli/releases/download/v0.1.0/golang-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "86362587acabf6d11a2465203e64117d0e71bb8d9f9501d501e50d06b2b021f9"

      def install
        bin.install "golang-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/golang-cli/releases/download/v0.1.0/golang-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "055f2fbcc39c3a3f87b51e4150a9f90abf3773bbad059595355d93fea2fc3e56"
      def install
        bin.install "golang-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/golang-cli/releases/download/v0.1.0/golang-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "827144c12fe512b7562c489e573e9d50144c9304d468a6bd494ae8bb9580a634"
      def install
        bin.install "golang-cli"
      end
    end
  end

  test do
    system "#{bin}/golang-cli", "version"
  end
end
